//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class creo_dbEntities : DbContext
    {
        public creo_dbEntities()
            : base("name=creo_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<meetingAttendance> meetingAttendances { get; set; }
        public virtual DbSet<meetingRepRelationship> meetingRepRelationships { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<meetingType> meetingTypes { get; set; }
        public virtual DbSet<meetingTypeScrapeHelper> meetingTypeScrapeHelpers { get; set; }
        public virtual DbSet<organisation> organisations { get; set; }
        public virtual DbSet<representative> representatives { get; set; }
        public virtual DbSet<role> roles { get; set; }
    }
}
