//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetingTypeScrapeHelper
    {
        public int meetScrapeID { get; set; }
        public Nullable<int> meetTypeID { get; set; }
        public Nullable<int> orgID { get; set; }
        public string startWord { get; set; }
        public string endWord { get; set; }
    
        public virtual meetingType meetingType { get; set; }
        public virtual organisation organisation { get; set; }
    }
}
