//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meeting()
        {
            this.meetingAttendances = new HashSet<meetingAttendance>();
        }
    
        public int meetID { get; set; }
        public Nullable<int> orgID { get; set; }
        public Nullable<int> meetTypeID { get; set; }
        public Nullable<System.DateTime> meetDate { get; set; }
        public string minuteUrl { get; set; }
        public string minuteType { get; set; }
        public string minuteText { get; set; }
        public string minuteFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetingAttendance> meetingAttendances { get; set; }
        public virtual meetingType meetingType { get; set; }
        public virtual organisation organisation { get; set; }
    }
}
