//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class representative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public representative()
        {
            this.meetingAttendances = new HashSet<meetingAttendance>();
            this.meetingRepRelationships = new HashSet<meetingRepRelationship>();
        }
    
        public int repID { get; set; }
        public string surname { get; set; }
        public string forename { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> orgID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetingAttendance> meetingAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetingRepRelationship> meetingRepRelationships { get; set; }
        public virtual organisation organisation { get; set; }
    }
}
